Add hot comment display
gaogaotiantian/biliscope pull request #180
Opened 2024-07-23 02:31 UTC by F-park

close #177

2024-07-23 03:17 UTC, F-park commented
无 API call，用 flex 压缩了 AI 总结的高度。

2024-07-23 16:56 UTC, F-park commented
支持了表情和内链的显示

2024-07-23 18:57 UTC, gaogaotiantian commented
这边发个预览图我看一下效果

2024-07-24 00:17 UTC, F-park commented
![image](https://github.com/user-attachments/assets/5d6b4d7c-52e0-4907-837d-3ec84e2960d1)
![image](https://github.com/user-attachments/assets/213f8d10-1c68-4e5c-9c7f-90269b17db4a)

2024-07-24 00:56 UTC, gaogaotiantian commented
这design不太行……这个comment首先肯定要在那个框里，现在这像流出来了……然后它在默认情况下，应该就是一行或者两行，鼠标悬停上去再做展开。现在这个design评论的部分太大了。评论的价值是要显著小于总结的，它应该只是一个辅助的内容。

另外，在没有总结的时候评论是什么效果？直接不放么？

2024-07-24 01:20 UTC, gaogaotiantian commented
![image](https://github.com/user-attachments/assets/4e5ae6a2-e57f-44ab-bf7a-fb857d34479b)
这个评论就没和上面的内容混淆啊。那个卡片肯定是最外框，评论我觉得应该是用style给展示出来，这样两个内容太难看了。

2024-07-24 03:38 UTC, F-park commented
改成这样呢？
![image](https://github.com/user-attachments/assets/a6e11f9c-c7aa-4d4f-81ca-be61bad22a06)
![image](https://github.com/user-attachments/assets/85cf1a80-fe7a-4d9f-a57b-de35ecb5d1bd)

2024-07-24 05:03 UTC, gaogaotiantian commented
没有AI总结的时候就不显示，没问题，不用单独显示一个热评。

我觉得我们还是把这个UI做的尽量和原生的像。不要去标注高赞还是热评，直接尽可能像原生UI那样，前面是评论者的名字，然后冒号后面接评论。字体颜色可以拉灰一点，然后看看那个icon好不好抄过来。我觉得应该尽可能减少我们自创的东西，如果有一些原来B站使用的style我们就去接近它。

2024-07-24 05:12 UTC, gaogaotiantian commented
另外还有一点要确认一下，现在在AI总结比较短的时候，是不会有滚动轴的，就是这个卡总是可以显示全。我希望加了这个feature之后依然是在AI总结比较短的时候总是可以全部显示的，包括热评和总结，不要让这个热评总改着总结一部分。

2024-07-24 05:15 UTC, F-park commented
可以显示，视频卡片有 `max-height: calc(50vh + 74px);`，两者加起来大于这个高度才会让 AI 总结显示滚动条

2024-07-24 06:09 UTC, F-park commented
和原生一样的样式，但我觉得这个灰色看着会很累。
![image](https://github.com/user-attachments/assets/7403f918-6c03-46b9-a96e-078f6b3455fc)
![image](https://github.com/user-attachments/assets/a69337f2-3533-4e6a-9627-163b355be57b)

2024-07-24 06:17 UTC, gaogaotiantian commented
`font-weight`一样么？我其实觉得好像还可以。右边的padding是不是太小了，这里两边padding控制一下。三个省略号依然是黑的。然后就是前面说的，如果没有AI总结，也不出这个热评了吧，单独出个热评好像有点怪。

2024-07-24 06:25 UTC, F-park commented
热评可以一定程度上看出视频质量，我觉得可以保留。高赞评论都没意义，那视频大概率是低质的。

2024-07-24 06:51 UTC, F-park commented
`font-weight` 确实不一样，被我从 400 加粗到 700，这应该是可以接受的吧。刚刚右边溢出了，现在应该可以了。
![image](https://github.com/user-attachments/assets/4487d119-ab4b-41dc-8dc8-53d5faf6eea0)

2024-07-27 18:09 UTC, gaogaotiantian commented
现在这个UI ok了，我觉得我们开始的时候，还是先只在有AI总结的video显示这个评论。如果未来大家有需求，认为这个评论在没有总结的视频也应该出现，我们可以再调整。因为我的感受是这个评论是对总结的一个补充，如果没有总结只有评论，它是比较单薄的，显示它还会占不少的空间。

2024-07-28 18:17 UTC, gaogaotiantian commented on css/videocard.css
> +    max-height: calc(50vh + 74px);
这里这个`+74px`有什么讲究么？直接`50vh`不行的么？

2024-07-28 18:42 UTC, gaogaotiantian requested changes
代码部分还是有一些不理想的地方，我们慢慢改。。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +    if (this.valid == null) {
这里是要干什么？`this.valid == null`只有最开始的时候是吧？你把html的部分初始化好是不是就行了？不懂为什么要再最前面加个这个。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +            document.getElementById("biliscope-ai-summary-popup").classList.remove("d-none");
你这里整个处理的方法有问题，逻辑弄得太乱了。

你在处理数据的时候，不应该做任何DOM上的操作。你处理数据只有一个目的，就是决定接下来要干什么。

你看我原来的整体逻辑，前面读数据的部分是只读数据的，后面的逻辑去“画”DOM，这是个基本的逻辑拆分，你现在全给混到一起了。

首先HTML的部分，你不能把三个div平行列出来，就是none, summary和reply。none自己是一个div，然后summary和reply肯定在一个div里。要么就是把reply放到summary里，要么就是新建一个div去放它俩。这样你在后面control的时候，就不会存在说有三个DOM要你来回开关的。

然后读数据的时候，你只应该读数据。只要summary存在，`this.valid`就是`true`，而reply只更新数据层面的reply。

你可以分别在读conclusion和读reply的时候，调用`drawConclusion`和`drawReply`，而所有的对reply的DOM逻辑都应该在`drawReply`里完成，包括这个reply是不是显示。

下面的那个显示逻辑应该是基本不变的，可能有的id需要改一下。

你可能会遇到一个问题是上一个video的reply残留，或者reply和summary没法同步显示，这是没事的，user card也会有这个问题。不要把这个updateData搞得乱七八糟。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +                    hotCommentItem.style = "width:1.4em;height:1.4em;vertical-align:text-bottom;";
这里如果你已经用`createElement`建立element了，就用css去控制style。只有直接写html的时候可能为了方便我们去inline style。而且你这个item还不少style呢，包括下面的hover style，完全没必要去做onmouseover

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +    let hotComment;
这里直接`let hotComment = `就好了啊。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +    if(!hotComment) {
`if`后面的空格

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +            let emotes = content?.emote;
能用const的就const一下。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +            let hotComments, hotCommentItem;
这里这个`hotComments`感觉像是若干个`hotComment`（你前面定义的），而不是`hotComment`拆分出来的若干部分。命名最好改一下。

2024-07-28 18:42 UTC, gaogaotiantian commented on scripts/videoui.js
> +                    delete jump_urls_copy[s];
这里需要显式删除么？

2024-07-29 01:38 UTC, F-park commented on scripts/videoui.js
> +                    delete jump_urls_copy[s];
只标蓝第一次出现，后面出现的就当作普通文本了。前面正则那里控制不了分割次数，就这样处理了。

2024-07-29 01:44 UTC, F-park commented on scripts/videoui.js
> +    if (this.valid == null) {
每次 updateTarget 的时候都会设置 `this.valid = null`，等于每次 updateData 之前就是 null ，放在  html 里语义就变了。

2024-07-29 03:58 UTC, gaogaotiantian commented on css/videocard.css
> +}
这儿怎么把我最后一行的空行给改没了。

2024-07-29 04:01 UTC, gaogaotiantian commented on scripts/videoui.js
> +    document.getElementById("biliscope-hot-comment-wrapper").classList.add("d-none");
是不是只有一种情况不显示，就是在没有reply的时候？那你这个代码是不是可以直接放到下面的判断去？因为你这个函数不是async的，在开始加`d-none`然后算到最后拿掉，应该对DOM的渲染没有影响吧。

2024-07-29 04:01 UTC, gaogaotiantian commented on scripts/videoui.js
> +    if(hotComment) {
if后面的空格

2024-07-29 04:06 UTC, gaogaotiantian commented on scripts/videoui.js
> +                separators = separators.concat(Object.keys(emotes));
这里是不是可以直接
```javascript
separators = separators.concat(Object.keys(content?.emotes || {}));
```

2024-07-29 04:06 UTC, gaogaotiantian commented on scripts/videoui.js
> +            let regexStr = separators.map(s =>
这个regex有点复杂，稍微写个注释给个例子说明一下它在干啥。

2024-07-29 04:11 UTC, gaogaotiantian commented on scripts/videoui.js
> +                    jump_urls_copy[s] = undefined;
`undefined`是这么用的么……我不确定啊，但是我自己好像从来没有显示给一个东西assign undefined过。如果这里确实有需求删掉`s`这个key，可以delete。稍微注释一下为什么要这么干就行。

2024-07-29 18:01 UTC, gaogaotiantian commented on scripts/videoui.js
> +        if (this.valid) {
你把这里改成这样的话，如果先完成的API是`view`，那就会在完全没有数据的情况下直接显示东西，这是没必要的。`this.valid`是`null`代表没有足够数据判断，啥也不现实，`false`代表确定了，显示没有AI总结，`true`代表确定了，显示AI总结和热评。

2024-07-30 04:40 UTC, merged

2024-07-30 04:40 UTC, gaogaotiantian commented
辛苦~