Fix user card display in bili-comments
gaogaotiantian/biliscope pull request #181
Opened 2024-07-23 08:41 UTC by F-park

close #179

2024-07-23 20:46 UTC, gaogaotiantian commented
sitescript那里我觉得是不是不用标注了，因为新的comment里都加了一个attribute `data-user-profile-id`，可以直接读。你让`getTarget`多返回一个field `id`之类的，然后直接用这个`id`，这样这个逻辑可以在`getTarget`里解决。

load那个部分，400ms试一下是唯一的解法么？没有点相对优雅的触发方式么？

测z-index那个现在这样还对么？是不是有可能导致被上层的内容挡住啊。

2024-07-24 02:24 UTC, F-park commented
一三弄好了。

二没找到更好的方法来判断。MutationObserver 不能观察 shadowroot 里面的元素，得用三个 MutationObserver 嵌套才能观察到变化。

2024-07-24 19:14 UTC, gaogaotiantian requested changes
我们可以暂时先这样，到时候看看有没有更好的解决方案，把一些style的问题改了就ok了。

2024-07-24 19:14 UTC, gaogaotiantian commented on scripts/load.js
> +        let hookComment = () => {
这个let可以const吧

2024-07-24 19:14 UTC, gaogaotiantian commented on scripts/load.js
> +                    ?.shadowRoot.querySelector("bili-comment-renderer")) {
我们这里把所有的换行统一一下吧。产生带`.`的换行都直接把`.`对齐最开始那个parent。比如
```
if (!document.
     .querySelector(..))
```
然后保证`.shadowRoot`不成为开头的那个element，不好读，因为`.shadowRoot`一般是紧跟着上一个element的。

下面还有几个换行也是，53行56行之类的。

2024-07-24 19:14 UTC, gaogaotiantian commented on scripts/load.js
> +                    ?.shadowRoot.querySelector("bili-comment-renderer")) {
另外这里设置个`maxRetry`之类的，如果未来B站再改格式，我们不要在这里玩命找。

2024-07-24 19:14 UTC, gaogaotiantian commented on scripts/load.js
> +                    replies = element.shadowRoot.querySelector("bili-comment-replies-renderer")
`const replies = ...`

2024-07-25 07:03 UTC, F-park commented on scripts/load.js
> +                    ?.shadowRoot.querySelector("bili-comment-renderer")) {
改成了 `20*500ms=10s` 的寻找时间，应该足够了

2024-07-25 17:43 UTC, gaogaotiantian requested changes
还是一些style的事。

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +                .querySelector("bili-comment-thread-renderer")?.shadowRoot
我更倾向于这里的`.`和`d`对齐，而不是`!`

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +        let retry = 20;
这里的variable definition是没意义的，你实际用到它的时候在很下面。而且我觉得直接传个constant就行了。

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +                    .querySelector("bili-comment-renderer").shadowRoot
这里也是，`.`和`e`对齐

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +                .querySelector("bili-comment-replies-renderer").shadowRoot
这里的`.`也是和`element`的`e`对齐。就是所有的`.`都去找它最开始的那个root的第一个字母

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +                        .querySelector("bili-comment-user-info")
这个也是和`r`对齐。

2024-07-25 17:43 UTC, gaogaotiantian commented on scripts/load.js
> +            setTimeout(() => hookComment(retry), 500);
这里retry其实没必要单独写个var我觉得。实在特别想写可以直接在这里定义一个`const maxRetry = 20`然后pass一下。

2024-07-26 17:42 UTC, gaogaotiantian commented on scripts/load.js
> +            let el;
这个`el`为啥要定义在外面？为啥不定义在61行？

2024-07-26 17:45 UTC, gaogaotiantian commented on scripts/load.js
> +            let el;
而且我个人可能更倾向于对于两个element用不同的variable name，因为它们是有意义的，比如`const avatar = XXX`然后`avatar.addEventListener`

2024-07-26 23:18 UTC, gaogaotiantian commented on scripts/load.js
> +                     .querySelector("bili-comment-renderer").shadowRoot
这里的`.`对齐有问题。

2024-07-26 23:18 UTC, gaogaotiantian commented on scripts/load.js
> +                    const avatar = reply.shadowRoot
这里就不是avatar了，avatar是头像，这里应该是userInfo或者userName之类的。

2024-07-27 00:49 UTC, F-park commented on scripts/load.js
> +                    const avatar = reply.shadowRoot
![image](https://github.com/user-attachments/assets/a6562461-9e47-4a08-9237-90f84cbd039f)

确实是 avatar，`bili-comment-user-info` 这个 tag 没有 `getElementById` 方法。

2024-07-27 01:11 UTC, gaogaotiantian commented on scripts/load.js
> +                    const avatar = reply.shadowRoot
哎这里是avatar啊，那用户的名字那里的触发做了么？

这里是不是`querySelector("#user-avatar")`好一些。

2024-07-27 18:07 UTC, merged