增加分区跳转链接
gaogaotiantian/biliscope pull request #58
Opened 2023-07-09 11:24 UTC by ste1hi

在卡片上点击分区标签跳转到该分区。
如：点击这里
![image](https://github.com/gaogaotiantian/biliscope/assets/49638961/90de1d9e-bead-4312-b2b7-c4c3f6c45c23)
跳转至
![image](https://github.com/gaogaotiantian/biliscope/assets/49638961/e77fb6aa-23c4-4a13-9d06-d29d94f5c21f)

2023-07-09 18:29 UTC, gaogaotiantian requested changes
代码本身没问题，有一些小细节要处理一下~感谢增加这个数据。

2023-07-09 18:29 UTC, gaogaotiantian commented on scripts/constants.js
> +BILIBILI_VIDEO_TYPE_MAP = {"1": "动画", "24": "MAD·AMV", "25": "MMD·3D", "47": "短片·手书·配音", "210": "手办·模玩", "86": "特摄", "253": "动漫杂谈", "27": "综合", "13": "番剧", "51": "番剧资讯", "152": "官方延伸", "32": "完结动画",
为啥改了我几个标签呢？这种细小的修改是要说明一下的。

我扫了一眼，你把一些“资讯”改成了对应分区的资讯，但是在B站上的这个分区显示的就是资讯，所以我希望和B站保持一致。

2023-07-09 18:29 UTC, gaogaotiantian commented on scripts/constants.js
> +BILIBILI_VIDEO_TYPE_LINK = {"1": "douga", "24": "douga/mad", "25": "douga/mmd", "47": "douga/voice", "210": "douga/garage_kit", "86": "douga/tokusatsu", "253": "douga/acgntalks", "27": "douga/other",
这个部分不要换行了，和前面保持一致就行，不是需要人来读的文件。

2023-07-09 18:29 UTC, gaogaotiantian commented on scripts/ui.js
> -
不要偷偷删掉我的空格~

2023-07-09 18:56 UTC, ste1hi commented on scripts/constants.js
> +BILIBILI_VIDEO_TYPE_MAP = {"1": "动画", "24": "MAD·AMV", "25": "MMD·3D", "47": "短片·手书·配音", "210": "手办·模玩", "86": "特摄", "253": "动漫杂谈", "27": "综合", "13": "番剧", "51": "番剧资讯", "152": "官方延伸", "32": "完结动画",
因为如果都叫资讯，点进去却是不同的分区显得很奇怪（甚至B站还有一个大的资讯分区）。

另外，修改了一些已经改名的分区，如：“中国舞”->“国风舞蹈”。

2023-07-10 00:51 UTC, gaogaotiantian commented on scripts/ui.js
> -
我会建议在每次PR之后，在github上看一下diff，这样就不会出现你加了空格没意识到的情况。

2023-07-10 00:53 UTC, gaogaotiantian commented on scripts/constants.js
> +BILIBILI_VIDEO_TYPE_MAP = {"1": "动画", "24": "MAD·AMV", "25": "MMD·3D", "47": "短片·手书·配音", "210": "手办·模玩", "86": "特摄", "253": "动漫杂谈", "27": "综合", "13": "番剧", "51": "番剧资讯", "152": "官方延伸", "32": "完结动画",
我理解你的意图，甚至在方向上认同你的观点，但是我觉得这个解决方案是不理想的。因为你的这个改动其实是完全原创的，B站的那个sub标签确实就叫“资讯”。在程序里，我觉得不应该做这样的修改。未来或许可以去通过增加主分区来进行区别，但是目前我认为还是直接保留子分区的名字，这样起码是保证统一性的。

改名的分区是ok的。

2023-07-10 03:04 UTC, ste1hi commented on scripts/ui.js
> -
好的

2023-07-10 03:09 UTC, ste1hi commented on scripts/constants.js
> +BILIBILI_VIDEO_TYPE_MAP = {"1": "动画", "24": "MAD·AMV", "25": "MMD·3D", "47": "短片·手书·配音", "210": "手办·模玩", "86": "特摄", "253": "动漫杂谈", "27": "综合", "13": "番剧", "51": "番剧资讯", "152": "官方延伸", "32": "完结动画",
好的，已经改回去了

2023-07-10 03:14 UTC, gaogaotiantian commented on scripts/ui.js
> -
这里还是没改啊，还是多出来四个空格啊……

2023-07-10 03:19 UTC, ste1hi commented on scripts/ui.js
> -
啊这，现在改了

2023-07-10 03:20 UTC, merged

2023-07-10 03:20 UTC, gaogaotiantian commented
感谢贡献！