Some small UI improvements 一些小的UI改进
gaogaotiantian/biliscope pull request #7
Opened 2023-03-11 06:25 UTC by painttist

1. Changed border-radius 4px -> 8px to maintain a more similar style
2. Changed the height of the header 120px -> 100px because it is unnecessary information. Would consider reduce it further to 85px which aligns with the usual info panel.
3. Adds muted badges to help reduce layout shift which help improve readability at a glance
4. Adds a transition (and corresponding wrapper) to the canvas element so the loading feels less abrupt & more polished.

------
很喜欢这个小插件，意外有用，感谢分享
1. 改了边框圆角 4px -> 8px 保持风格和B站统一
2. 缩小了头图 120px -> 100px 无用信息建议缩减，B站自己的是 85px 左右
3. 添加了灰色的标签，目的是减少加载过程中的布局变化来辅助高速信息阅读（也有更高质量的感觉）
4. 添加了 canvas 的过度让整体感觉更丝滑。

2023-03-11 07:00 UTC, gaogaotiantian commented
有没有截图可以看一下你改了什么。

B站的id card有（起码）两种，一个是在动态里的，一个是关注列表里的。我完全照抄的关注列表里的，border-radius是4px，然后height也是现在的这个。你看的应该是动态的，所以不一样。

canvas的部分你用的show和muted？这是不是依赖于bootstrap的？

2023-03-11 07:51 UTC, painttist commented
静态
![image](https://user-images.githubusercontent.com/50148803/224472274-0592661e-d44c-4751-9c0b-2581b12bc6f4.png)

因为大部分是加载过程中和动画效果，所以不太方便截图，就录了个屏
https://user-images.githubusercontent.com/50148803/224472341-d4eabf1c-04ec-4c3c-bd06-66cc9019cb85.mp4

2023-03-11 08:01 UTC, painttist commented
是的，我看的是一般视频页面右边，移动到UP头像上的那个弹出框。考虑到主要使用场景是主页和视频推荐，页面上大部分元素都是 6px 的 border radius，我觉得这个弹出框的 border radius 6px-8px 比较合适，4px稍微小了点。

show 和 muted 我添加了对应需要的 javascript 和 css。名字主要是比较常用简洁，可以更改。不需要 bootstrap。因为有配合ID来写 css query，应该也不用担心和其它样式有冲突。

2023-03-11 18:51 UTC, gaogaotiantian requested changes
很感谢你的贡献哈~我认为canvas的动画部分是很好的。其他的地方我也是有一些我的看法，如果你不同意的话我们也可以继续讨论（当然我还是有最终的决定权 : P ）

2023-03-11 18:51 UTC, gaogaotiantian commented on css/idcard.css
> +    /* border-radius: 4px 4px 0 0; */
这里是留还是不留呢？是相当于在上面overflow的地方处理掉了么？

2023-03-11 18:51 UTC, gaogaotiantian commented on css/idcard.css
> +    height: 100px;
上面这个image我们暂时保持原状吧，确实上半部分是没有信息量的，但是和评论区的card比，这个template的头像是顶进这个背景一点的，我感觉上面大一点会平衡一些。

2023-03-11 18:51 UTC, gaogaotiantian commented on css/idcard.css
> +    vertical-align: top;
这里ok，把那个comment删了吧，那个应该是在commit的时候写的，不需要留在代码里。

2023-03-11 18:51 UTC, gaogaotiantian commented on css/idcard.css
> +#biliscope-id-card .biliscope-badge.muted {
不需要“无”这个tag，下面细说，这个css拿掉。

2023-03-11 18:51 UTC, gaogaotiantian commented on css/idcard.css
> +/* .user-card-m-exp {
这里是个什么东西……为啥留在了css里

2023-03-11 18:51 UTC, gaogaotiantian commented on scripts/ui.js
> +            <div id="word-cloud-canvas-wrapper"><canvas id="word-cloud-canvas" style="width: 100%; height: 0"></canvas></div>
html写开，div像上面一样两个tag自己占一行，canvas写到中间。

2023-03-11 18:51 UTC, gaogaotiantian commented on scripts/ui.js
> +            canvas.parentNode.className = "";
这里不要直接overwrite `className`，这个操作比较危险。用classList.remove()，别影响其他的class（虽然现在没有，但是未来有了这里会藏雷）。

2023-03-11 18:51 UTC, gaogaotiantian commented on scripts/ui.js
> +        tagList.innerHTML = `<span class="biliscope-badge muted">无</span>`;
这里拿掉这个“无”，因为它是个非常奇怪的tag。如果一个用户没有任何的视频，那它的“投稿数”会显示为0，这时候没有tag这一行就是很容易理解的事情。加个“无”反而显得画蛇添足。而且由于网络延迟的原因，在拿到投稿数之前，就是没有tag的状态，这时候从一个tag“无”，变成应该有的tag，是个很怪的transition……

2023-03-11 18:51 UTC, gaogaotiantian commented on scripts/ui.js
> +
这里的comment不应该出现，不要comment没有发生的事情。你应该去在css里解释为什么show是一半（如果你想解释），而不是说，如果这件事没发生，应该怎么处理。

还有这里也是变classList。

另外有关这个class name的选择，show有点过于常见了。你不光要考虑到你的css对其它component的影响（你说了因为css被限制在这个card里，所以不会影响到其它的component），你也要考虑到外部css对它的影响啊。如果外面有一个定义到全局的`show` class，你这里就可能出奇怪的很难以发现的bug。所以在css的名字上，也是选择一个不那么容易冲突的名字（可以考虑用一些我们的identifier像`biliscope`去做前缀啥的）。

2023-03-12 05:19 UTC, painttist commented on css/idcard.css
> +    /* border-radius: 4px 4px 0 0; */
是的，这里的 border radius 因为上面的 overflow 所以不需要了

2023-03-12 05:20 UTC, painttist commented on css/idcard.css
> +    height: 100px;
嗯如果是有 wordcloud 的情况下，确实也挺平衡的

2023-03-12 05:44 UTC, painttist commented on css/idcard.css
> +/* .user-card-m-exp {
.user-card-m-exp 是B站自己的那个 id card 的 class，可以通过这个 css 达到替换原本 id card 的效果。问题主要出在多人投稿的时候会影响快速关注。目前这些多余的 comments 都删掉了

2023-03-12 05:45 UTC, painttist commented on scripts/ui.js
> +            canvas.parentNode.className = "";
很合理

2023-03-12 05:49 UTC, painttist commented on scripts/ui.js
> +        tagList.innerHTML = `<span class="biliscope-badge muted">无</span>`;
这里我一开始的设计目的是减少 layout shift，也就是加载的时候和完成的时候，用户会不会看到界面跳动的情况。考虑到这里的 tag “无” 在确实没有投稿的情况下会有歧义，确实可以移除。目前加载过程中，头图大小，人物图片等目前似乎都有一定的 layout shift，没有完善的加载状态，所以这里可以先删掉，之后再考虑一并解决。

2023-03-12 05:53 UTC, painttist commented on scripts/ui.js
> +
嗯这里的 comments 确实不太有用。
这里的 show 确实可能会导致外部 css 造成影响，取名有点随意了。目前修改成了 biliscope-canvas-show
classList 问题也修复了

2023-03-12 05:56 UTC, painttist commented
谢谢这么细心的Review！这是我第一次尝试提交 Pull Request。虽然内容很简单但是很多细节确实有点随意，学习了。上述的问题应该都解决好了。

2023-03-12 07:01 UTC, gaogaotiantian requested changes
加上一个空行就可以啦！

我一直觉得其实code review是一个很好的审视自己代码的方式。我说的不一定是对的，但是在交流的过程中可能我们都会有所提升。

2023-03-12 07:01 UTC, gaogaotiantian commented on css/idcard.css
> +}
这里要补一个空行，文件结尾加空行是好习惯。

2023-03-12 07:07 UTC, painttist commented on css/idcard.css
> +}
好的，添加上了

2023-03-12 07:09 UTC, merged